---
title: "South Carolina Retirement System Solvency Analysis"
author: "Prepared by: Pension Integrity Project at Reason Foundation. 2022—Preliminary Draft"
date: "07/14/2021"
output:
  powerpoint_presentation:
    reference_doc: template_deck.pptx
  beamer_presentation: default
always_allow_html: true
fontsize: 9pt
font-family: Arial
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  #dev = "svg",
  fig.width = 12,
  fig.height = 7
  #Font size (Graphs + Text)
  #Source line
  #Header
  
)

year <- 2021
#Update linePlot() for Treasury functionality
#Update linePlot() for shaded UAL area/line plot
#Create glPlot() w/ function to turn "interactive" parameter TRUE/FALSE to create Plotly graph (eventually use database data)
#Create barPlot() w/ manual ready data + database calculated Neg.Amo + interest on Debt
#
```



### Current Contributions Are Actuarially Insufficient (2021-2052) w/ R (linePlot())

```{r crises, dpi=400, echo = FALSE, fig.cap = "Source: Pension Integrity Project actuarial forecast of SCRS.", fig.width=8, fig.height=5, message=FALSE, warning=FALSE}

library(reasontheme)
library(pensionviewr)
library(ggplot2)
library(tidyverse)
library(tseries)
library(data.table)
library(readr)
library(rsconnect)
library(dplyr)
library(plyr)

urlfile <- "https://raw.githubusercontent.com/ANiraula/SCRS_FModel/main/SCRS.FModel_ERC_ADEC.csv"
stress <- data.frame(
  read_csv(url(urlfile), col_names = TRUE, na = c(""), skip_empty_rows = TRUE, col_types = NULL)
)

stress[1:4,2:5] <- seq(0.1556, 0.1856, by = 0.01)
stress[5:20,2] <- 0.1856
#stress[21:33,2] <- seq(0.1856, 0.0656, by = -0.01)

DPF.data <- data.table(stress)
colnames(DPF.data) <- c("year",
                        "assumption", "model",
                        "crisis", "2crises")
#View(DPF.data)

DPF.data <- DPF.data %>% select("year",
                        "assumption", "model",
                         "2crises","crisis")


linePlot <- function (data, title = NULL, caption = FALSE, grid = FALSE, 
  treasury = FALSE, inv.returns = TRUE, ticks = TRUE, font = NULL, 
  yaxisMin = 0, yaxisMax = NULL, yaxisSeq = 5, yaxisScale = 100, 
  format = NULL, str = 20, labelY = NULL, lab1 = NULL, lab2 = NULL, 
  lab3 = NULL, lab4 = NULL, lab5 = NULL, lab6 = NULL) 
{
  reasontheme::set_reason_theme(style = "slide")
  
   plotTheme <- ggplot2::theme(   panel.grid.major = element_blank(),
                                 panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
                                 plot.margin = margin(0, 0.5,0,0, "cm"),
                                 axis.text.y = element_text(size=12, color = "black"),
                                 axis.text.x = element_text(size=12, color = "black", angle = 0, hjust = 0.5, vjust = -1),
                                 axis.title = element_text(size = 12, face = "bold"),
                                 legend.text = element_text(size = 12),
                                 legend.title = element_blank(),
                                 text = element_text(family = "Calibri"))
   
  x <- length(data$year)
  data <- data.frame(data) %>% dplyr::mutate_all(as.numeric)
  if (isTRUE(treasury)) {
    urlfile <- "https://raw.githubusercontent.com/ReasonFoundation/databaseR/master/files/treasury.csv"
    treasury <- read_csv(url(urlfile), col_names = TRUE, 
      na = c(""), skip_empty_rows = TRUE, col_types = NULL)
    treasury$year <- as.numeric(treasury$year)
    treasury <- treasury %>% filter(year>2000 & year < 2020)
    data$year <- as.numeric(data$year)
    treasury <- data.table(treasury %>% filter(year > min(data$year - 
      1)))
    data <- data %>% select(year, arr)
    data <- data.table(data)
    data <- cbind(data, treasury[, 2])
    data <- data.frame(data) %>% dplyr::mutate_all(as.numeric)
    data <- as.data.table(data)
    data$alt.discount <- NA
    diff <- (data[year == min(data$year)]$arr - data[year == 
      min(data$year)]$X30.treasury)
    data$alt.discount <- data$X30.treasury + diff
  }
  geomean <- function(x) {
    x <- as.vector(na.omit(x))
    x <- x + 1
    exp(mean(log(x))) - 1
  }
  if (isTRUE(inv.returns)) {
    data$return_1yr <- as.numeric(data$return_1yr)
    returns <- data$return_1yr
    last <- length(returns)
    rolling <- matrix(NA, last, 1)
    rolling[last] <- as.numeric(geomean(returns[(last - 
      9):last]))
    for (i in 1:(last - 10)) {
      rolling[last - i] <- geomean(returns[(last - 9 - 
        i):(last - i)])
    }
    rolling <- data.table(rolling)
    returns[(last - 9):last]
    returns[(last - 9 + 1):(last - 1)]
    data <- data.table(cbind(data, rolling))
    data <- data %>% select(year, return_1yr, ava_return, 
      arr, V1)
  }
  colnames(data) <- c("year", if (!is_null(lab1)) {
    paste(lab1)
  }, if (!is_null(lab2)) {
    paste(lab2)
  }, if (!is_null(lab3)) {
    paste(lab3)
  }, if (!is_null(lab4)) {
    paste(lab4)
  }, if (!is_null(lab5)) {
    paste(lab5)
  }, if (!is_null(lab6)) {
    paste(lab6)
  })
  ##Crate line types per variable
data <- as.data.table(data)
  graph <- data.table(melt(data, id.vars = "year"))
  graph <- graph %>% filter(year > 2020)
  lineColors <- c(
 palette_reason$LightBlue,  palette_reason$SatBlue, palette_reason$LightOrange,palette_reason$LightOrange)#, palette_reason$Yellow, palette_reason$Yellow)
  options(repr.plot.width = 1, repr.plot.height = 0.75)
  ggplot2::ggplot(graph, ggplot2::aes(x = year, y = yaxisScale * 
    value, group = variable, linetype=variable)) + ggplot2::geom_line(ggplot2::aes(colour = str_wrap(factor(variable), 
    str)), size = 1) + 
    ggplot2::geom_hline(yintercept = 0, color = "black") + 
    ggplot2::scale_colour_manual(values = lineColors) + 
    scale_linetype_manual(values=c("solid", "dashed",  "dashed","solid"))+#Assigns line types set to each line
    ggplot2::scale_y_continuous(breaks = seq(yaxisMin, if (!is.null(yaxisMax)) {
      yaxisMax
    }
    else {
      max(graph$value) * yaxisScale * 1.2
    }, by = yaxisSeq), limits = c(yaxisMin, if (!is.null(yaxisMax)) {
      yaxisMax
    } else {
      max(graph$value) * yaxisScale * 1.2
    }), labels = function(b) {
      if (format == "%") {
        paste0(round(b, 0), "%")
      }
      else if (format == "$") {
        paste0("$", round(b, 0))
      }
      else {
        paste0(format, round(b, 0))
      }
    }, expand = c(0, 0)) + ggplot2::scale_x_continuous(breaks = seq(min(graph$year), 
    max(graph$year), by = 2), expand = c(0, 0)) + labs(x = element_blank(), 
    y = labelY)+
    theme(legend.direction = "vertical", legend.box = "horizontal", 
    legend.position = c(0.9, 0.9)) + labs(title = paste(title), caption = ifelse(isTRUE(caption), 
    paste("reason.org/pensions"), paste(""))) + ggplot2::theme(axis.ticks = if (isFALSE(ticks)) {
    ggplot2::element_blank()
  }
  else {
    ggplot2::element_line()
  }) + ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
    color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
    color = "black")) + ggplot2::theme(panel.grid.major.y = element_line(colour = ifelse(isTRUE(grid), 
    paste(palette_reason$SpaceGrey), "white"), size = (2))) +
     plotTheme
}

crises <- linePlot(DPF.data, title = NULL, caption = FALSE, grid = FALSE, 
                  treasury = FALSE, inv.returns = FALSE, ticks = TRUE, font = "Calibri",
                  yaxisMin = 0, yaxisMax = 36, yaxisSeq = 4,
                  yaxisScale = 100, format = "%", str = 80,
                  labelY = "Employer Contribution (% Payroll)", 
                  lab1 = "Baseline (Statutory)",
                  lab2 = "6% Constant Annual Return (ADEC)",
                  lab3 = "2022-25 Crisis & 2037-40 Crisis & 6% Returns (ADEC)",
                  lab5 = "2022-25 Crisis & 6% Returns (ADEC)")
                 

crises
```

### SCRS Solvency Degrades Under Crisis Scenarios (2021-2052) w/ R (linePlot())

```{r fr.crises, dpi=400, echo = FALSE, fig.cap = "Source: Pension Integrity Project actuarial forecast of SCRS.", fig.width=8, fig.height=5,  message=FALSE, warning=FALSE}

library(reasontheme)
library(pensionviewr)
library(ggplot2)
library(tidyverse)
library(tseries)
library(data.table)
library(readr)
library(rsconnect)
library(dplyr)
library(plyr)

urlfile <- "https://raw.githubusercontent.com/ANiraula/SCRS_FModel/main/SCRS.FModel_FR_Statutory.csv"
stress <- data.frame(
  read_csv(url(urlfile), col_names = TRUE, na = c(""), skip_empty_rows = TRUE, col_types = NULL)
)
#View(stress[3,2:5])
#View(stress)

DPF.data <- data.table(stress)
colnames(DPF.data) <- c("year",
                        "assumption", "model",
                        "crisis", "2crises")
#View(DPF.data)

DPF.data <- DPF.data %>% select("year",
                        "assumption", "model",
                         "2crises","crisis")



linePlot <- function (data, title = NULL, caption = FALSE, grid = FALSE, 
  treasury = FALSE, inv.returns = TRUE, ticks = TRUE, font = NULL, 
  yaxisMin = 0, yaxisMax = NULL, yaxisSeq = 5, yaxisScale = 100, 
  format = NULL, str = 20, labelY = NULL, lab1 = NULL, lab2 = NULL, 
  lab3 = NULL, lab4 = NULL, lab5 = NULL, lab6 = NULL) 
{
  reasontheme::set_reason_theme(style = "slide")
  
   plotTheme <- ggplot2::theme(   panel.grid.major = element_blank(),
                                 panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
                                 plot.margin = margin(0, 0.5,0,0, "cm"),
                                 axis.text.y = element_text(size=12, color = "black"),
                                 axis.text.x = element_text(size=12, color = "black", angle = 0, hjust = 0.5, vjust = -1),
                                 axis.title = element_text(size = 12, face = "bold"),
                                 legend.text = element_text(size = 12),
                                 legend.title = element_blank(),
                                 text = element_text(family = "Calibri"))
   
  x <- length(data$year)
  data <- data.frame(data) %>% dplyr::mutate_all(as.numeric)
  if (isTRUE(treasury)) {
    urlfile <- "https://raw.githubusercontent.com/ReasonFoundation/databaseR/master/files/treasury.csv"
    treasury <- read_csv(url(urlfile), col_names = TRUE, 
      na = c(""), skip_empty_rows = TRUE, col_types = NULL)
    treasury$year <- as.numeric(treasury$year)
    treasury <- treasury %>% filter(year>2000 & year < 2020)
    data$year <- as.numeric(data$year)
    treasury <- data.table(treasury %>% filter(year > min(data$year - 
      1)))
    data <- data %>% select(year, arr)
    data <- data.table(data)
    data <- cbind(data, treasury[, 2])
    data <- data.frame(data) %>% dplyr::mutate_all(as.numeric)
    data <- as.data.table(data)
    data$alt.discount <- NA
    diff <- (data[year == min(data$year)]$arr - data[year == 
      min(data$year)]$X30.treasury)
    data$alt.discount <- data$X30.treasury + diff
  }
  geomean <- function(x) {
    x <- as.vector(na.omit(x))
    x <- x + 1
    exp(mean(log(x))) - 1
  }
  if (isTRUE(inv.returns)) {
    data$return_1yr <- as.numeric(data$return_1yr)
    returns <- data$return_1yr
    last <- length(returns)
    rolling <- matrix(NA, last, 1)
    rolling[last] <- as.numeric(geomean(returns[(last - 
      9):last]))
    for (i in 1:(last - 10)) {
      rolling[last - i] <- geomean(returns[(last - 9 - 
        i):(last - i)])
    }
    rolling <- data.table(rolling)
    returns[(last - 9):last]
    returns[(last - 9 + 1):(last - 1)]
    data <- data.table(cbind(data, rolling))
    data <- data %>% select(year, return_1yr, ava_return, 
      arr, V1)
  }
  colnames(data) <- c("year", if (!is_null(lab1)) {
    paste(lab1)
  }, if (!is_null(lab2)) {
    paste(lab2)
  }, if (!is_null(lab3)) {
    paste(lab3)
  }, if (!is_null(lab4)) {
    paste(lab4)
  }, if (!is_null(lab5)) {
    paste(lab5)
  }, if (!is_null(lab6)) {
    paste(lab6)
  })
  ##Crate line types per variable
data <- as.data.table(data)
  graph <- data.table(melt(data, id.vars = "year"))
  graph <- graph %>% filter(year > 2020)
  lineColors <- c(
  palette_reason$LightBlue,palette_reason$SatBlue, palette_reason$LightOrange,palette_reason$LightOrange)#, palette_reason$Yellow, palette_reason$Yellow)
  options(repr.plot.width = 1, repr.plot.height = 0.75)
  ggplot2::ggplot(graph, ggplot2::aes(x = year, y = yaxisScale * 
    value, group = variable, linetype=variable)) + ggplot2::geom_line(ggplot2::aes(colour = str_wrap(factor(variable), 
    str)), size = 1) + 
    ggplot2::geom_hline(yintercept = 0, color = "black") + 
    ggplot2::scale_colour_manual(values = lineColors) + 
    scale_linetype_manual(values=c("solid", "dashed",  "dashed","solid"))+#Assigns line types set to each line
    ggplot2::scale_y_continuous(breaks = seq(yaxisMin, if (!is.null(yaxisMax)) {
      yaxisMax
    }
    else {
      max(graph$value) * yaxisScale * 1.2
    }, by = yaxisSeq), limits = c(yaxisMin, if (!is.null(yaxisMax)) {
      yaxisMax
    } else {
      max(graph$value) * yaxisScale * 1.2
    }), labels = function(b) {
      if (format == "%") {
        paste0(round(b, 0), "%")
      }
      else if (format == "$") {
        paste0("$", round(b, 0))
      }
      else {
        paste0(format, round(b, 0))
      }
    }, expand = c(0, 0)) + ggplot2::scale_x_continuous(breaks = seq(min(graph$year), 
    max(graph$year), by = 2), expand = c(0, 0)) + labs(x = element_blank(), 
    y = labelY)+
    theme(legend.direction = "vertical", legend.box = "horizontal", 
    legend.position = c(1.01, 0.14)) + labs(title = paste(title), caption = ifelse(isTRUE(caption), 
    paste("reason.org/pensions"), paste(""))) + ggplot2::theme(axis.ticks = if (isFALSE(ticks)) {
    ggplot2::element_blank()
  }
  else {
    ggplot2::element_line()
  }) + ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
    color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
    color = "black")) + ggplot2::theme(panel.grid.major.y = element_line(colour = ifelse(isTRUE(grid), 
    paste(palette_reason$SpaceGrey), "white"), size = (2))) +
     plotTheme
}

fr.crises <- linePlot(DPF.data, title = NULL, caption = FALSE, grid = FALSE, 
                  treasury = FALSE, inv.returns = FALSE, ticks = TRUE, font = "Calibri",
                  yaxisMin = 0, yaxisMax = 120, yaxisSeq = 10,
                  yaxisScale = 100, format = "%", str = 80,
                  labelY = "Funded Status (Actuarial Value)", 
                  lab1 = "Baseline (Statutory)",
                  lab2 = "6% Constant Annual Return (Statutory)",
                  lab3 = "2022-25 Crisis & 2037-40 Crisis & 6% Returns (Statutory)",
                  lab5 = "2022-25 Crisis & 6% Returns (Statutory)")
                 
fr.crises
```

### Pension Debt Will Likely Grow (2021-2052) w/ R (linePlot())

```{r ual, dpi=400, echo = FALSE, fig.cap = "Source: Pension Integrity Project actuarial forecast of SCRS.", fig.width=8, fig.height=5, message=FALSE, warning=FALSE}

library(reasontheme)
library(pensionviewr)
library(ggplot2)
library(tidyverse)
library(tseries)
library(data.table)
library(readr)
library(rsconnect)
library(dplyr)
library(plyr)

urlfile <- "https://raw.githubusercontent.com/ANiraula/SCRS_FModel/main/SCRS.FModel_UAL_Statutory.csv"
stress <- data.frame(
  read_csv(url(urlfile), col_names = TRUE, na = c(""), skip_empty_rows = TRUE, col_types = NULL)
)
#stress[1:4,2] <- seq(0.1556, 0.1856, by = 0.01)
#stress[5:20,2] <- 0.1856
#stress[21:33,2] <- seq(0.1856, 0.0656, by = -0.01)

DPF.data <- data.table(stress)
colnames(DPF.data) <- c("year",
                        "assumption", "model",
                        "crisis", "2crises")
#View(DPF.data)
DPF.data <- DPF.data %>% select("year",
                        "assumption", "model",
                         "2crises","crisis")
DPF.data$model[26:34] <- 0
#View(DPF.data$model[26:34])

linePlot <- function (data, title = NULL, caption = FALSE, grid = FALSE, 
  treasury = FALSE, inv.returns = TRUE, ticks = TRUE, font = NULL, 
  yaxisMin = 0, yaxisMax = NULL, yaxisSeq = 5, yaxisScale = 100, 
  format = NULL, str = 20, labelY = NULL, lab1 = NULL, lab2 = NULL, 
  lab3 = NULL, lab4 = NULL, lab5 = NULL, lab6 = NULL) 
{
  reasontheme::set_reason_theme(style = "slide")
  
   plotTheme <- ggplot2::theme(   panel.grid.major = element_blank(),
                                 panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
                                 plot.margin = margin(0, 0.5,0,0, "cm"),
                                 axis.text.y = element_text(size=12, color = "black"),
                                 axis.text.x = element_text(size=12, color = "black", angle = 0, hjust = 0.5, vjust = -1),
                                 axis.title = element_text(size = 12, face = "bold"),
                                 legend.text = element_text(size = 12),
                                 legend.title = element_blank(),
                                 text = element_text(family = "Calibri"))
   
  x <- length(data$year)
  data <- data.frame(data) %>% dplyr::mutate_all(as.numeric)
  if (isTRUE(treasury)) {
    urlfile <- "https://raw.githubusercontent.com/ReasonFoundation/databaseR/master/files/treasury.csv"
    treasury <- read_csv(url(urlfile), col_names = TRUE, 
      na = c(""), skip_empty_rows = TRUE, col_types = NULL)
    treasury$year <- as.numeric(treasury$year)
    treasury <- treasury %>% filter(year>2000 & year < 2020)
    data$year <- as.numeric(data$year)
    treasury <- data.table(treasury %>% filter(year > min(data$year - 
      1)))
    data <- data %>% select(year, arr)
    data <- data.table(data)
    data <- cbind(data, treasury[, 2])
    data <- data.frame(data) %>% dplyr::mutate_all(as.numeric)
    data <- as.data.table(data)
    data$alt.discount <- NA
    diff <- (data[year == min(data$year)]$arr - data[year == 
      min(data$year)]$X30.treasury)
    data$alt.discount <- data$X30.treasury + diff
  }
  geomean <- function(x) {
    x <- as.vector(na.omit(x))
    x <- x + 1
    exp(mean(log(x))) - 1
  }
  if (isTRUE(inv.returns)) {
    data$return_1yr <- as.numeric(data$return_1yr)
    returns <- data$return_1yr
    last <- length(returns)
    rolling <- matrix(NA, last, 1)
    rolling[last] <- as.numeric(geomean(returns[(last - 
      9):last]))
    for (i in 1:(last - 10)) {
      rolling[last - i] <- geomean(returns[(last - 9 - 
        i):(last - i)])
    }
    rolling <- data.table(rolling)
    returns[(last - 9):last]
    returns[(last - 9 + 1):(last - 1)]
    data <- data.table(cbind(data, rolling))
    data <- data %>% select(year, return_1yr, ava_return, 
      arr, V1)
  }
  colnames(data) <- c("year", if (!is_null(lab1)) {
    paste(lab1)
  }, if (!is_null(lab2)) {
    paste(lab2)
  }, if (!is_null(lab3)) {
    paste(lab3)
  }, if (!is_null(lab4)) {
    paste(lab4)
  }, if (!is_null(lab5)) {
    paste(lab5)
  }, if (!is_null(lab6)) {
    paste(lab6)
  })
  ##Crate line types per variable
data <- as.data.table(data)
  graph <- data.table(melt(data, id.vars = "year"))
  graph <- graph %>% filter(year > 2020)
   lineColors <- c(
  palette_reason$LightBlue,palette_reason$SatBlue, palette_reason$LightOrange,palette_reason$LightOrange)#, palette_reason$Yellow, palette_reason$Yellow)
  options(repr.plot.width = 1, repr.plot.height = 0.75)
  ggplot2::ggplot(graph, ggplot2::aes(x = year, y = yaxisScale * 
    value, group = variable, linetype=variable)) + ggplot2::geom_line(ggplot2::aes(colour = str_wrap(factor(variable), 
    str)), size = 1) + 
    ggplot2::geom_hline(yintercept = 0, color = "black") + 
    ggplot2::scale_colour_manual(values = lineColors) + 
    scale_linetype_manual(values=c("solid", "dashed",  "dashed","solid"))+#Assigns line types set to each line
    ggplot2::scale_y_continuous(breaks = seq(yaxisMin, if (!is.null(yaxisMax)) {
      yaxisMax
    }
    else {
      max(graph$value) * yaxisScale * 1.2
    }, by = yaxisSeq), limits = c(yaxisMin, if (!is.null(yaxisMax)) {
      yaxisMax
    } else {
      max(graph$value) * yaxisScale * 1.2
    }), labels = function(b) {
      if (format == "%") {
        paste0(round(b, 0), "%")
      }
      else if (format == "$") {
        paste0("$", round(b, 0))
      }
      else {
        paste0(format, round(b, 0))
      }
    }, expand = c(0, 0)) + ggplot2::scale_x_continuous(breaks = seq(min(graph$year), 
    max(graph$year), by = 2), expand = c(0, 0)) + labs(x = element_blank(), 
    y = labelY)+
    theme(legend.direction = "vertical", legend.box = "horizontal", 
    legend.position = c(1.5, 1.5)) + labs(title = paste(title), caption = ifelse(isTRUE(caption), 
    paste("reason.org/pensions"), paste(""))) + ggplot2::theme(axis.ticks = if (isFALSE(ticks)) {
    ggplot2::element_blank()
  }
  else {
    ggplot2::element_line()
  }) + ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
    color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
    color = "black")) + ggplot2::theme(panel.grid.major.y = element_line(colour = ifelse(isTRUE(grid), 
    paste(palette_reason$SpaceGrey), "white"), size = (2))) +
     plotTheme
}

ual <- linePlot(DPF.data, title = NULL, caption = FALSE, grid = FALSE, 
                  treasury = FALSE, inv.returns = FALSE, ticks = TRUE, font = "Calibri",
                  yaxisMin = 0, yaxisMax = 40, yaxisSeq = 4,
                  yaxisScale = 1/1000, format = "$", str = 80,
                  labelY = "Unfunded Actuarial Liability (in $Billions)", 
                  lab1 = "Baseline",
                  lab2 = "6% Constant Annual Return",
                  lab3 = "2022-25 Crisis & 2037-40 Crisis & 6% Returns",
                  lab5 = "2022-25 Crisis & 6% Returns")
                 

ual
```

### 30-Year Funded Ratio Forecast - Statutory (Assumed) w/ R (barPlot())

```{r stochasticFR, dpi=400, echo = FALSE, fig.cap = "Source: Pension Integrity Project actuarial forecast of SCRS.", fig.width=8, fig.height=5, message=FALSE, warning=FALSE}

rm(list=ls())

library(reasontheme)
library(pensionviewr)
library(ggplot2)
library(tidyverse)
library(tseries)
library(data.table)
library(readr)
library(rsconnect)
library(dplyr)
library(plyr)
library(DT)
library(scales)

###################

barPlot <- function (data = NULL, net.amo = FALSE, contributions = FALSE, 
  compound.gl = TRUE, gl.url = "https://raw.githubusercontent.com/ReasonFoundation/GraphicsR/master/PERSI_GL2.csv", 
  str = 25, stochastic = FALSE, stochastic.url = "https://raw.githubusercontent.com/ReasonFoundation/databaseR/master/files/perctest2.csv", 
  stochastic.alpha = 0.4, Ymax = 25, Ymin = 0, Ybreak = 5, 
  yaxisScale = 1/1e+09, interactive = FALSE, font = "Calibri", 
  lab1 = "Investment Experience", lab2 = "Benefit Changes", 
  lab3 = "Changes to Actuarial Methods & Assumptions", lab4 = "Deviations from Demographic Assumptions", 
  lab5 = "Negative Amortization", lab6 = "Gains From Pay Increases Not Given", 
  lab7 = "Net Change to Unfunded Liability", lab8 = NULL, 
  lab9 = NULL) 
{
  if (!is.null(data)) {
    reason.data <- data
  }
  plotTheme <- ggplot2::theme(panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), 
    plot.margin = margin(0.5, 0.5, 0, 0, "cm"), axis.text.y = element_text(size = 12, 
      color = "black"), axis.text.x = element_text(size = 12, 
      color = "black", angle = 0, hjust = 0.5, vjust = -1), 
      legend.spacing.x = unit(0.1, 'cm'),
    axis.title = element_text(size = 12, face = "bold"), 
    legend.text = element_text(size = 12,margin = margin(t = 1)), legend.title = element_blank(), 
    text = element_text(family = "Calibri"))
  
  if (isTRUE(net.amo)) {
    if (is_null(reason.data$interest_on_debt_dollar)) {
      reason.data$interest_on_debt_dollar <- 0
      n <- length(reason.data$interest_on_debt_dollar)
      for (i in (1:n)) {
        reason.data$interest_on_debt_dollar[i] <- (reason.data$unfunded_actuarially_accrued_liabilities_dollar[i] + 
          reason.data$total_nc[i]) * reason.data$investment_return_assumption_for_gasb_reporting[i] - 
          (reason.data$total_contribution_dollar[i] * 
            reason.data$investment_return_assumption_for_gasb_reporting[i]) * 
            0.5
      }
    }
    reason.data$total_amortization_payment_percentage <- as.numeric(reason.data$total_amortization_payment_percentage)
    reason.data$payroll2 <- as.numeric(reason.data$payroll2)
    reason.data$interest_on_debt_dollar <- as.numeric(reason.data$interest_on_debt_dollar)
    reason.data$net.amo <- 0
    reason.data$amo.payments <- 0
    reason.data$amo.payments <- if (sum(!is.na(reason.data$amortization_payment_total_amount) != 0)) {
      reason.data$amortization_payment_total_amount
    }
    else {
      reason.data$total_amortization_payment_percentage * 
        reason.data$payroll2
    }
    
    
    reason.data$net.amo <- -(reason.data$amo.payments+
      reason.data$interest_on_debt_dollar)
    

    reason.data <- data.table(reason.data %>% select(year, 
      interest_on_debt_dollar, amo.payments, net.amo))
    # reason.data$over <- ifelse(reason.data$net.amo > 0, 
    #   reason.data$net.amo, NA)
    # reason.data$net.amo <- ifelse(reason.data$net.amo < 
    #   0, reason.data$net.amo, NA)
    reason.data$amo.payments <- -(reason.data$amo.payments)
    reason.data <- data.table(reason.data)

    colnames(reason.data) <- c("year", "Interest Accrued on Unfunded Liabilities", 
      "Contributions Towards Unfunded Liabilities", "Net Amortization: Contributions Above/Below Interest on Unfunded Liabilities")
    
    reason.data <- melt(reason.data, vars = "Net Amortization: Contributions Above/Below Interest on Unfunded Liabilities")
    
    reason.data <- data.frame(reason.data[22:84, ])

    x <- data.table(seq(2001, 2021, by = 1))
    x <- rbind(x, x, x)
    reason.data <- cbind(x, reason.data)
    reason.data <- data.frame(reason.data)
    graph <- ggplot(reason.data, aes(x = V1, y = value, 
      fill = variable)) + geom_bar(stat = "identity", 
      position = position_dodge(width = 0.9), width = 0.8) + 
      theme(panel.grid.major.y = element_line(colour = "white", 
        size = 3)) + scale_y_continuous(labels = function(x) paste0("$", 
      x/yaxisScale), name = if (isTRUE(net.amo)) {
      "Unfunded Liability Payments (in $Millions)"
    }
    else {
      "Employer Contributions v. ADC (in $Millions)"
    }, breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), expand = c(0, 0)) + ggplot2::geom_hline(yintercept = 0, 
      color = "black") + scale_fill_manual(values = c(palette_reason$SatBlue, 
      palette_reason$Orange, palette_reason$LightBlue, palette_reason$Green)) + 
      ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
        color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
      color = "black")) + scale_x_continuous(labels = function(x) paste0(x, 
      ""), name = "", breaks = seq(2001, 2022, by = 2), 
      limits = c(2001, 2022), expand = c(0, 0)) + theme_bw() + theme(axis.line = element_line(), panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), panel.border = element_blank(), 
      panel.background = element_blank()) + theme(legend.position = c(0.45, 
      0.9)) + plotTheme 
  }
  else if (isTRUE(contributions)) {
    reason.data <- reason.data %>% select(year, actuarially_required_contribution_dollar, 
      actuarially_required_contribution_paid_percentage, 
      employer_contribution_regular_dollar)
    reason.data <- reason.data %>% transmute(year = year, 
      adec = actuarially_required_contribution_dollar, 
      adec_paid = actuarially_required_contribution_dollar * 
        actuarially_required_contribution_paid_percentage, 
      adec_unpaid = actuarially_required_contribution_dollar - 
        (actuarially_required_contribution_dollar * 
          actuarially_required_contribution_paid_percentage))
    reason.data <- data.frame(reason.data)
    graph <- ggplot(reason.data) + 
      
      geom_col(aes(x = year, 
      y = adec, fill = "Contributions Not Made"), position = "stack", width = 0.5) + 
      
      geom_col(aes(x = year, y = ifelse((adec_paid > adec), 
        adec_paid, 0), fill = "Excess Contributions"), 
        position = "stack", width = 0.5) + 
      
      geom_col(aes(x = year, 
      y = ifelse((adec_paid <= adec), adec_paid, adec), 
      fill = "Actual Contributions"), position = "stack", width = 0.5) + 
      
      geom_line(aes(x = year, y = adec, color = "Actuarially Determined Contribution"), 
        fill = palette_reason$Yellow, size = 1) + theme(panel.grid.major.y = element_line(colour = "white", 
      size = 3)) + scale_y_continuous(labels = function(x) paste0("$", 
      x/yaxisScale), name = if (isTRUE(net.amo)) {
      "Unfunded Liability Payments (in $Millions)"
    }
    else {
      "Employer Contributions v. ADC (in $Millions)"
    }, breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), expand = c(0, 0)) + scale_fill_manual(values = c(palette_reason$SpaceGrey, 
      palette_reason$Red, palette_reason$Green, palette_reason$Yellow)) + 
      scale_color_manual(values = c(palette_reason$Yellow)) + 
      ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
        color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
      color = "black")) + scale_x_continuous(labels = function(x) paste0(x, 
      ""), name = "", breaks = seq(2001, 2020, by = 2), 
      limits = c(2000, 2021), expand = c(0, 0)) + theme_bw() + theme(axis.line = element_line(), panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), panel.border = element_blank(), 
      panel.background = element_blank()) + theme(legend.position = c(0.25, 
      0.8))+ plotTheme 
  }
  else if (isTRUE(stochastic)) {
    
    
    data_perc <- read_csv(url(stochastic.url), col_names = TRUE, 
      na = c(""), skip_empty_rows = TRUE, col_types = NULL)
    data_perc <- data.frame(data_perc)
    
    data_perc <- cbind(seq(2019, 2052, by = 1), data_perc)
    data_perc[, 2:4] <- data_perc[, 2:4] * 100
    colnames(data_perc) <- c("year", "X25", "X50", "X75")
    data_perc <- data.frame(data_perc)

    graph <- ggplot(data_perc, aes(x = year, y = `X25`)) + 
      geom_col(aes(x = year, y = `X75`, fill = "Range of Reasonable Outcomes"), 
        alpha = stochastic.alpha) + 
      geom_col(aes(x = year, y = `X25`), fill = "white") + 
      geom_line(aes(x = year, y = `X50`, color = "Median"), size = 2) + 
      scale_fill_manual(values = c(palette_reason$DarkBlue, "white", palette_reason$Orange)) + 
      theme(panel.grid.major.y = element_line(colour = "white", 
      size = 3)) + scale_y_continuous(labels = function(x) paste0(x, 
      "%"), breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), name = "Funded Ratio (Actuarial Value)", 
      expand = c(0, 0)) + scale_color_manual(values = c(palette_reason$Orange)) + 
      ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
        color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
      color = "black")) + scale_x_continuous(labels = function(x) paste0(x, 
      ""), name = "", breaks = seq(2020, 2053, by = 2), 
      limits = c(2020, 2053), expand = c(0, 0)) + theme_bw() +
      theme(axis.line = element_line(), panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), panel.border = element_blank(), 
      panel.background = element_blank()) + theme(legend.position = c(0.25, 
      0.8))+ plotTheme 
  }
  else if (isTRUE(compound.gl)) {
    urlfile = gl.url
    data <- read_csv(url(urlfile), col_names = TRUE, na = c(""), 
      skip_empty_rows = TRUE, col_types = NULL)
    data <- as.data.table(data)
    data <- data %>% replace(is.na(.), 0)
    data <- data.frame(data)
    data2 <- data.frame(data)
    for (i in (2:(length(data[, 1])))) {
      data2[i, 2:length(data)] <- data2[i, 2:length(data)] + 
        data2[(i - 1), 2:length(data)]
    }
    data2 <- data.table(data2 %>% mutate_all(as.numeric))
    reason.data <- data.frame(data2)
    colnames(reason.data) <- c("year", lab1, lab2, lab3, 
      lab4, lab5, lab6, if (!is_null(lab7)) {
        paste(lab7)
      }, if (!is_null(lab8)) {
        paste(lab8)
      }, if (!is_null(lab9)) {
        paste(lab9)
      })
    names <- colnames(reason.data)
    graph <- ggplot(reason.data) + geom_col(aes(x = year, 
      y = reason.data[, 2] * yaxisScale, fill = str_wrap(as.character(names[2]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 3] * yaxisScale, fill = str_wrap(as.character(names[3]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 4] * yaxisScale, fill = str_wrap(as.character(names[4]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 5] * yaxisScale, fill = str_wrap(as.character(names[5]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 6] * yaxisScale, fill = str_wrap(as.character(names[6]), 
        str)), position = "stack") + geom_line(aes(x = year, 
      y = reason.data[, length(names)] * yaxisScale, color = str_wrap(paste(last(names)), 
        str)), size = 1.25) + ggplot2::geom_hline(yintercept = 0, 
      color = "black") + scale_fill_manual(values = c(palette_reason$LightRed, 
      palette_reason$Orange, palette_reason$LightOrange, 
      palette_reason$Green, palette_reason$Red, palette_reason$Yellow, 
      palette_reason$SatBlue)) + scale_color_manual(values = c("black")) + 
      theme_bw() + theme(axis.line = element_line(), 
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
      panel.border = element_blank(), panel.background = element_blank()) + 
      theme(legend.position = "right") + theme(legend.title = element_blank()) + 
      labs(x = element_blank(), y = "Compound Unfunded Actuarial Liability (in $ Billions)") + 
      ggplot2::scale_x_continuous(breaks = seq(min(reason.data$year), 
        max(reason.data$year), by = 2), expand = c(0, 
        0)) + ggplot2::scale_y_continuous(labels = function(x) paste0("$", 
      x), breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), expand = c(0, 0)) + if (!is.null(lab7)) {
      geom_col(aes(x = year, y = reason.data[, 7] * yaxisScale, 
        fill = str_wrap(as.character(names[7]), str)), 
        position = "stack") + plotTheme
    }
    else if (!is.null(lab7) & !is.null(lab8)) {
      geom_col(aes(x = year, y = reason.data[, 7] * yaxisScale, 
        fill = str_wrap(as.character(names[7]), str)), 
        position = "stack") + geom_col(aes(x = year, 
        y = reason.data[, 8] * yaxisScale, fill = str_wrap(as.character(names[8]), 
          str)), position = "stack")
    }
    else if (!is.null(lab7) & !is.null(lab8) & !is.null(lab9)) {
      geom_col(aes(x = year, y = reason.data[, 7] * yaxisScale, 
        fill = str_wrap(as.character(names[7]), str)), 
        position = "stack") + geom_col(aes(x = year, 
        y = reason.data[, 8] * yaxisScale, fill = str_wrap(as.character(names[8]), 
          str)), position = "stack") + geom_col(aes(x = year, 
        y = reason.data[, 9] * yaxisScale, fill = str_wrap(as.character(names[9]), 
          str)), position = "stack")
    }
  }
  if (isTRUE((interactive))) {
    graph <- ggplotly(graph)
  }
  graph
}


stochasticFR <- barPlot(
  data = NULL, 
  net.amo = FALSE, 
  contributions = FALSE, 
  compound.gl = FALSE,
  gl.url = "https://raw.githubusercontent.com/ReasonFoundation/GraphicsR/master/PERSI_GL2.csv",
  str = 25,
  stochastic = TRUE, 
  stochastic.url = "https://raw.githubusercontent.com/ANiraula/SCRS_FModel/main/SCRS.FModel_FR_Statutory_Stoch.csv",
  Ymax = 180,
  Ymin = 0,
  Ybreak = 10,
  yaxisScale = 1/1000000000, 
  stochastic.alpha = 0.95,
  interactive = FALSE,
  lab1 = "Investment Experience", 
  lab2 = "Benefit Changes",
  lab3 = "Changes to Actuarial Methods & Assumptions",
  lab4 = "Deviations from Demographic Assumptions",
  lab5 = "Negative Amortization",
  lab6 = "Gains From Pay Increases Not Given",
  lab7 = "Net Change to Unfunded Liability",
  lab8 = NULL,
  lab9 = NULL)

stochasticFR
```

### 30-Year Funded Ratio Forecast - Statutory (Conservative) w/ R (barPlot())

```{r stochasticFR2, dpi=400, echo = FALSE, fig.cap = "Source: Pension Integrity Project actuarial forecast of SCRS.", fig.width=8, fig.height=5, message=FALSE, warning=FALSE}

rm(list=ls())

library(reasontheme)
library(pensionviewr)
library(ggplot2)
library(tidyverse)
library(tseries)
library(data.table)
library(readr)
library(rsconnect)
library(dplyr)
library(plyr)
library(DT)
library(scales)


######################
####### BARPLOT ######
######################

barPlot <- function (data = NULL, net.amo = FALSE, contributions = FALSE, 
  compound.gl = TRUE, gl.url = "https://raw.githubusercontent.com/ReasonFoundation/GraphicsR/master/PERSI_GL2.csv", 
  str = 25, stochastic = FALSE, stochastic.url = "https://raw.githubusercontent.com/ReasonFoundation/databaseR/master/files/perctest2.csv", 
  stochastic.alpha = 0.4, Ymax = 25, Ymin = 0, Ybreak = 5, 
  yaxisScale = 1/1e+09, interactive = FALSE, font = "Calibri", 
  lab1 = "Investment Experience", lab2 = "Benefit Changes", 
  lab3 = "Changes to Actuarial Methods & Assumptions", lab4 = "Deviations from Demographic Assumptions", 
  lab5 = "Negative Amortization", lab6 = "Gains From Pay Increases Not Given", 
  lab7 = "Net Change to Unfunded Liability", lab8 = NULL, 
  lab9 = NULL) 
{
  if (!is.null(data)) {
    reason.data <- data
  }
  plotTheme <- ggplot2::theme(panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), 
    plot.margin = margin(0.5, 0.5, 0, 0, "cm"), axis.text.y = element_text(size = 12, 
      color = "black"), axis.text.x = element_text(size = 12, 
      color = "black", angle = 0, hjust = 0.5, vjust = -1), 
      legend.spacing.x = unit(0.1, 'cm'),
    axis.title = element_text(size = 12, face = "bold"), 
    legend.text = element_text(size = 12,margin = margin(t = 1)), legend.title = element_blank(), 
    text = element_text(family = "Calibri"))
  
  if (isTRUE(net.amo)) {
    if (is_null(reason.data$interest_on_debt_dollar)) {
      reason.data$interest_on_debt_dollar <- 0
      n <- length(reason.data$interest_on_debt_dollar)
      for (i in (1:n)) {
        reason.data$interest_on_debt_dollar[i] <- (reason.data$unfunded_actuarially_accrued_liabilities_dollar[i] + 
          reason.data$total_nc[i]) * reason.data$investment_return_assumption_for_gasb_reporting[i] - 
          (reason.data$total_contribution_dollar[i] * 
            reason.data$investment_return_assumption_for_gasb_reporting[i]) * 
            0.5
      }
    }
    reason.data$total_amortization_payment_percentage <- as.numeric(reason.data$total_amortization_payment_percentage)
    reason.data$payroll2 <- as.numeric(reason.data$payroll2)
    reason.data$interest_on_debt_dollar <- as.numeric(reason.data$interest_on_debt_dollar)
    reason.data$net.amo <- 0
    reason.data$amo.payments <- 0
    reason.data$amo.payments <- if (sum(!is.na(reason.data$amortization_payment_total_amount) != 0)) {
      reason.data$amortization_payment_total_amount
    }
    else {
      reason.data$total_amortization_payment_percentage * 
        reason.data$payroll2
    }
    
    
    reason.data$net.amo <- -(reason.data$amo.payments+
      reason.data$interest_on_debt_dollar)
    

    reason.data <- data.table(reason.data %>% select(year, 
      interest_on_debt_dollar, amo.payments, net.amo))
    # reason.data$over <- ifelse(reason.data$net.amo > 0, 
    #   reason.data$net.amo, NA)
    # reason.data$net.amo <- ifelse(reason.data$net.amo < 
    #   0, reason.data$net.amo, NA)
    reason.data$amo.payments <- -(reason.data$amo.payments)
    reason.data <- data.table(reason.data)

    colnames(reason.data) <- c("year", "Interest Accrued on Unfunded Liabilities", 
      "Contributions Towards Unfunded Liabilities", "Net Amortization: Contributions Above/Below Interest on Unfunded Liabilities")
    
    reason.data <- melt(reason.data, vars = "Net Amortization: Contributions Above/Below Interest on Unfunded Liabilities")
    
    reason.data <- data.frame(reason.data[22:84, ])

    x <- data.table(seq(2001, 2021, by = 1))
    x <- rbind(x, x, x)
    reason.data <- cbind(x, reason.data)
    reason.data <- data.frame(reason.data)
    graph <- ggplot(reason.data, aes(x = V1, y = value, 
      fill = variable)) + geom_bar(stat = "identity", 
      position = position_dodge(width = 0.9), width = 0.8) + 
      theme(panel.grid.major.y = element_line(colour = "white", 
        size = 3)) + scale_y_continuous(labels = function(x) paste0("$", 
      x/yaxisScale), name = if (isTRUE(net.amo)) {
      "Unfunded Liability Payments (in $Millions)"
    }
    else {
      "Employer Contributions v. ADC (in $Millions)"
    }, breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), expand = c(0, 0)) + ggplot2::geom_hline(yintercept = 0, 
      color = "black") + scale_fill_manual(values = c(palette_reason$SatBlue, 
      palette_reason$Orange, palette_reason$LightBlue, palette_reason$Green)) + 
      ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
        color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
      color = "black")) + scale_x_continuous(labels = function(x) paste0(x, 
      ""), name = "", breaks = seq(2001, 2022, by = 2), 
      limits = c(2001, 2022), expand = c(0, 0)) + theme_bw() + theme(axis.line = element_line(), panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), panel.border = element_blank(), 
      panel.background = element_blank()) + theme(legend.position = c(0.45, 
      0.9)) + plotTheme 
  }
  else if (isTRUE(contributions)) {
    reason.data <- reason.data %>% select(year, actuarially_required_contribution_dollar, 
      actuarially_required_contribution_paid_percentage, 
      employer_contribution_regular_dollar)
    reason.data <- reason.data %>% transmute(year = year, 
      adec = actuarially_required_contribution_dollar, 
      adec_paid = actuarially_required_contribution_dollar * 
        actuarially_required_contribution_paid_percentage, 
      adec_unpaid = actuarially_required_contribution_dollar - 
        (actuarially_required_contribution_dollar * 
          actuarially_required_contribution_paid_percentage))
    reason.data <- data.frame(reason.data)
    graph <- ggplot(reason.data) + 
      
      geom_col(aes(x = year, 
      y = adec, fill = "Contributions Not Made"), position = "stack", width = 0.5) + 
      
      geom_col(aes(x = year, y = ifelse((adec_paid > adec), 
        adec_paid, 0), fill = "Excess Contributions"), 
        position = "stack", width = 0.5) + 
      
      geom_col(aes(x = year, 
      y = ifelse((adec_paid <= adec), adec_paid, adec), 
      fill = "Actual Contributions"), position = "stack", width = 0.5) + 
      
      geom_line(aes(x = year, y = adec, color = "Actuarially Determined Contribution"), 
        fill = palette_reason$Yellow, size = 1) + theme(panel.grid.major.y = element_line(colour = "white", 
      size = 3)) + scale_y_continuous(labels = function(x) paste0("$", 
      x/yaxisScale), name = if (isTRUE(net.amo)) {
      "Unfunded Liability Payments (in $Millions)"
    }
    else {
      "Employer Contributions v. ADC (in $Millions)"
    }, breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), expand = c(0, 0)) + scale_fill_manual(values = c(palette_reason$SpaceGrey, 
      palette_reason$Red, palette_reason$Green, palette_reason$Yellow)) + 
      scale_color_manual(values = c(palette_reason$Yellow)) + 
      ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
        color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
      color = "black")) + scale_x_continuous(labels = function(x) paste0(x, 
      ""), name = "", breaks = seq(2001, 2020, by = 2), 
      limits = c(2000, 2021), expand = c(0, 0)) + theme_bw() + theme(axis.line = element_line(), panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), panel.border = element_blank(), 
      panel.background = element_blank()) + theme(legend.position = c(0.25, 
      0.8))+ plotTheme 
  }
  else if (isTRUE(stochastic)) {
    
    
    data_perc <- read_csv(url(stochastic.url), col_names = TRUE, 
      na = c(""), skip_empty_rows = TRUE, col_types = NULL)
    data_perc <- data.frame(data_perc)
    
    data_perc <- cbind(seq(2019, 2052, by = 1), data_perc)
    data_perc[, 2:4] <- data_perc[, 2:4] * 100
    colnames(data_perc) <- c("year", "X25", "X50", "X75")
    data_perc <- data.frame(data_perc)

    graph <- ggplot(data_perc, aes(x = year, y = `X25`)) + 
      geom_col(aes(x = year, y = `X75`, fill = "Range of Reasonable Outcomes"), 
        alpha = stochastic.alpha) + 
      geom_col(aes(x = year, y = `X25`), fill = "white") + 
      geom_line(aes(x = year, y = `X50`, color = "Median"), size = 2) + 
      scale_fill_manual(values = c(palette_reason$DarkBlue, "white", palette_reason$Orange)) + 
      theme(panel.grid.major.y = element_line(colour = "white", 
      size = 3)) + scale_y_continuous(labels = function(x) paste0(x, 
      "%"), breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), name = "Funded Ratio (Actuarial Value)", 
      expand = c(0, 0)) + scale_color_manual(values = c(palette_reason$Orange)) + 
      ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
        color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
      color = "black")) + scale_x_continuous(labels = function(x) paste0(x, 
      ""), name = "", breaks = seq(2020, 2053, by = 2), 
      limits = c(2020, 2053), expand = c(0, 0)) + theme_bw() +
      theme(axis.line = element_line(), panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), panel.border = element_blank(), 
      panel.background = element_blank()) + theme(legend.position = c(0.25, 
      0.8))+ plotTheme 
  }
  else if (isTRUE(compound.gl)) {
    urlfile = gl.url
    data <- read_csv(url(urlfile), col_names = TRUE, na = c(""), 
      skip_empty_rows = TRUE, col_types = NULL)
    data <- as.data.table(data)
    data <- data %>% replace(is.na(.), 0)
    data <- data.frame(data)
    data2 <- data.frame(data)
    for (i in (2:(length(data[, 1])))) {
      data2[i, 2:length(data)] <- data2[i, 2:length(data)] + 
        data2[(i - 1), 2:length(data)]
    }
    data2 <- data.table(data2 %>% mutate_all(as.numeric))
    reason.data <- data.frame(data2)
    colnames(reason.data) <- c("year", lab1, lab2, lab3, 
      lab4, lab5, lab6, if (!is_null(lab7)) {
        paste(lab7)
      }, if (!is_null(lab8)) {
        paste(lab8)
      }, if (!is_null(lab9)) {
        paste(lab9)
      })
    names <- colnames(reason.data)
    graph <- ggplot(reason.data) + geom_col(aes(x = year, 
      y = reason.data[, 2] * yaxisScale, fill = str_wrap(as.character(names[2]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 3] * yaxisScale, fill = str_wrap(as.character(names[3]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 4] * yaxisScale, fill = str_wrap(as.character(names[4]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 5] * yaxisScale, fill = str_wrap(as.character(names[5]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 6] * yaxisScale, fill = str_wrap(as.character(names[6]), 
        str)), position = "stack") + geom_line(aes(x = year, 
      y = reason.data[, length(names)] * yaxisScale, color = str_wrap(paste(last(names)), 
        str)), size = 1.25) + ggplot2::geom_hline(yintercept = 0, 
      color = "black") + scale_fill_manual(values = c(palette_reason$LightRed, 
      palette_reason$Orange, palette_reason$LightOrange, 
      palette_reason$Green, palette_reason$Red, palette_reason$Yellow, 
      palette_reason$SatBlue)) + scale_color_manual(values = c("black")) + 
      theme_bw() + theme(axis.line = element_line(), 
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
      panel.border = element_blank(), panel.background = element_blank()) + 
      theme(legend.position = "right") + theme(legend.title = element_blank()) + 
      labs(x = element_blank(), y = "Compound Unfunded Actuarial Liability (in $ Billions)") + 
      ggplot2::scale_x_continuous(breaks = seq(min(reason.data$year), 
        max(reason.data$year), by = 2), expand = c(0, 
        0)) + ggplot2::scale_y_continuous(labels = function(x) paste0("$", 
      x), breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), expand = c(0, 0)) + if (!is.null(lab7)) {
      geom_col(aes(x = year, y = reason.data[, 7] * yaxisScale, 
        fill = str_wrap(as.character(names[7]), str)), 
        position = "stack") + plotTheme
    }
    else if (!is.null(lab7) & !is.null(lab8)) {
      geom_col(aes(x = year, y = reason.data[, 7] * yaxisScale, 
        fill = str_wrap(as.character(names[7]), str)), 
        position = "stack") + geom_col(aes(x = year, 
        y = reason.data[, 8] * yaxisScale, fill = str_wrap(as.character(names[8]), 
          str)), position = "stack")
    }
    else if (!is.null(lab7) & !is.null(lab8) & !is.null(lab9)) {
      geom_col(aes(x = year, y = reason.data[, 7] * yaxisScale, 
        fill = str_wrap(as.character(names[7]), str)), 
        position = "stack") + geom_col(aes(x = year, 
        y = reason.data[, 8] * yaxisScale, fill = str_wrap(as.character(names[8]), 
          str)), position = "stack") + geom_col(aes(x = year, 
        y = reason.data[, 9] * yaxisScale, fill = str_wrap(as.character(names[9]), 
          str)), position = "stack")
    }
  }
  if (isTRUE((interactive))) {
    graph <- ggplotly(graph)
  }
  graph
}


###################

stochasticFR2 <- barPlot(
  data = NULL, 
  net.amo = FALSE, 
  contributions = FALSE, 
  compound.gl = FALSE,
  gl.url = "https://raw.githubusercontent.com/ReasonFoundation/GraphicsR/master/PERSI_GL2.csv",
  str = 25,
  stochastic = TRUE, 
  stochastic.url = "https://raw.githubusercontent.com/ANiraula/SCRS_FModel/main/SCRS.FModel_FR_Statutory_Stoch_Cons.csv",
  Ymax = 180,
  Ymin = 0,
  Ybreak = 10,
  yaxisScale = 1/1000000000, 
  stochastic.alpha = 0.95,
  interactive = FALSE,
  lab1 = "Investment Experience", 
  lab2 = "Benefit Changes",
  lab3 = "Changes to Actuarial Methods & Assumptions",
  lab4 = "Deviations from Demographic Assumptions",
  lab5 = "Negative Amortization",
  lab6 = "Gains From Pay Increases Not Given",
  lab7 = "Net Change to Unfunded Liability",
  lab8 = NULL,
  lab9 = NULL)

stochasticFR2
```

### 30-Year Employer Contribution Forecast - Statutory (Assumed) w/ R (barPlot())

```{r stochasticERC, dpi=400, echo = FALSE, fig.cap = "Source: Pension Integrity Project actuarial forecast of SCRS.", fig.width=8, fig.height=5, message=FALSE, warning=FALSE}

rm(list=ls())

library(reasontheme)
library(pensionviewr)
library(ggplot2)
library(tidyverse)
library(tseries)
library(data.table)
library(readr)
library(rsconnect)
library(dplyr)
library(plyr)
library(DT)
library(scales)

######################
####### BARPLOT ######
######################

barPlot2 <- function (data = NULL, net.amo = FALSE, contributions = FALSE, 
  compound.gl = TRUE, gl.url = "https://raw.githubusercontent.com/ReasonFoundation/GraphicsR/master/PERSI_GL2.csv", 
  str = 25, stochastic = FALSE, stochastic.url = "https://raw.githubusercontent.com/ReasonFoundation/databaseR/master/files/perctest2.csv", 
  stochastic.alpha = 0.4, Ymax = 25, Ymin = 0, Ybreak = 5, 
  yaxisScale = 1/1e+09, interactive = FALSE, font = "Calibri", 
  lab1 = "Investment Experience", lab2 = "Benefit Changes", 
  lab3 = "Changes to Actuarial Methods & Assumptions", lab4 = "Deviations from Demographic Assumptions", 
  lab5 = "Negative Amortization", lab6 = "Gains From Pay Increases Not Given", 
  lab7 = "Net Change to Unfunded Liability", lab8 = NULL, 
  lab9 = NULL) 
{
  if (!is.null(data)) {
    reason.data <- data
  }
  plotTheme <- ggplot2::theme(panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), 
    plot.margin = margin(0.5, 0.5, 0, 0, "cm"), axis.text.y = element_text(size = 12, 
      color = "black"), axis.text.x = element_text(size = 12, 
      color = "black", angle = 0, hjust = 0.5, vjust = -1), 
      legend.spacing.x = unit(0.1, 'cm'),
    axis.title = element_text(size = 12, face = "bold"), 
    legend.text = element_text(size = 12,margin = margin(t = 1)), legend.title = element_blank(), 
    text = element_text(family = "Calibri"))
  
  if (isTRUE(net.amo)) {
    if (is_null(reason.data$interest_on_debt_dollar)) {
      reason.data$interest_on_debt_dollar <- 0
      n <- length(reason.data$interest_on_debt_dollar)
      for (i in (1:n)) {
        reason.data$interest_on_debt_dollar[i] <- (reason.data$unfunded_actuarially_accrued_liabilities_dollar[i] + 
          reason.data$total_nc[i]) * reason.data$investment_return_assumption_for_gasb_reporting[i] - 
          (reason.data$total_contribution_dollar[i] * 
            reason.data$investment_return_assumption_for_gasb_reporting[i]) * 
            0.5
      }
    }
    reason.data$total_amortization_payment_percentage <- as.numeric(reason.data$total_amortization_payment_percentage)
    reason.data$payroll2 <- as.numeric(reason.data$payroll2)
    reason.data$interest_on_debt_dollar <- as.numeric(reason.data$interest_on_debt_dollar)
    reason.data$net.amo <- 0
    reason.data$amo.payments <- 0
    reason.data$amo.payments <- if (sum(!is.na(reason.data$amortization_payment_total_amount) != 0)) {
      reason.data$amortization_payment_total_amount
    }
    else {
      reason.data$total_amortization_payment_percentage * 
        reason.data$payroll2
    }
    
    
    reason.data$net.amo <- -(reason.data$amo.payments+
      reason.data$interest_on_debt_dollar)
    

    reason.data <- data.table(reason.data %>% select(year, 
      interest_on_debt_dollar, amo.payments, net.amo))
    # reason.data$over <- ifelse(reason.data$net.amo > 0, 
    #   reason.data$net.amo, NA)
    # reason.data$net.amo <- ifelse(reason.data$net.amo < 
    #   0, reason.data$net.amo, NA)
    reason.data$amo.payments <- -(reason.data$amo.payments)
    reason.data <- data.table(reason.data)

    colnames(reason.data) <- c("year", "Interest Accrued on Unfunded Liabilities", 
      "Contributions Towards Unfunded Liabilities", "Net Amortization: Contributions Above/Below Interest on Unfunded Liabilities")
    
    reason.data <- melt(reason.data, vars = "Net Amortization: Contributions Above/Below Interest on Unfunded Liabilities")
    
    reason.data <- data.frame(reason.data[22:84, ])

    x <- data.table(seq(2001, 2021, by = 1))
    x <- rbind(x, x, x)
    reason.data <- cbind(x, reason.data)
    reason.data <- data.frame(reason.data)
    graph <- ggplot(reason.data, aes(x = V1, y = value, 
      fill = variable)) + geom_bar(stat = "identity", 
      position = position_dodge(width = 0.9), width = 0.8) + 
      theme(panel.grid.major.y = element_line(colour = "white", 
        size = 3)) + scale_y_continuous(labels = function(x) paste0("$", 
      x/yaxisScale), name = if (isTRUE(net.amo)) {
      "Unfunded Liability Payments (in $Millions)"
    }
    else {
      "Employer Contributions v. ADC (in $Millions)"
    }, breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), expand = c(0, 0)) + ggplot2::geom_hline(yintercept = 0, 
      color = "black") + scale_fill_manual(values = c(palette_reason$SatBlue, 
      palette_reason$Orange, palette_reason$LightBlue, palette_reason$Green)) + 
      ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
        color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
      color = "black")) + scale_x_continuous(labels = function(x) paste0(x, 
      ""), name = "", breaks = seq(2001, 2022, by = 2), 
      limits = c(2001, 2022), expand = c(0, 0)) + theme_bw() + theme(axis.line = element_line(), panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), panel.border = element_blank(), 
      panel.background = element_blank()) + theme(legend.position = c(0.45, 
      0.9)) + plotTheme 
  }
  else if (isTRUE(contributions)) {
    reason.data <- reason.data %>% select(year, actuarially_required_contribution_dollar, 
      actuarially_required_contribution_paid_percentage, 
      employer_contribution_regular_dollar)
    reason.data <- reason.data %>% transmute(year = year, 
      adec = actuarially_required_contribution_dollar, 
      adec_paid = actuarially_required_contribution_dollar * 
        actuarially_required_contribution_paid_percentage, 
      adec_unpaid = actuarially_required_contribution_dollar - 
        (actuarially_required_contribution_dollar * 
          actuarially_required_contribution_paid_percentage))
    reason.data <- data.frame(reason.data)
    graph <- ggplot(reason.data) + 
      
      geom_col(aes(x = year, 
      y = adec, fill = "Contributions Not Made"), position = "stack", width = 0.5) + 
      
      geom_col(aes(x = year, y = ifelse((adec_paid > adec), 
        adec_paid, 0), fill = "Excess Contributions"), 
        position = "stack", width = 0.5) + 
      
      geom_col(aes(x = year, 
      y = ifelse((adec_paid <= adec), adec_paid, adec), 
      fill = "Actual Contributions"), position = "stack", width = 0.5) + 
      
      geom_line(aes(x = year, y = adec, color = "Actuarially Determined Contribution"), 
        fill = palette_reason$Yellow, size = 1) + theme(panel.grid.major.y = element_line(colour = "white", 
      size = 3)) + scale_y_continuous(labels = function(x) paste0("$", 
      x/yaxisScale), name = if (isTRUE(net.amo)) {
      "Unfunded Liability Payments (in $Millions)"
    }
    else {
      "Employer Contributions v. ADC (in $Millions)"
    }, breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), expand = c(0, 0)) + scale_fill_manual(values = c(palette_reason$SpaceGrey, 
      palette_reason$Red, palette_reason$Green, palette_reason$Yellow)) + 
      scale_color_manual(values = c(palette_reason$Yellow)) + 
      ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
        color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
      color = "black")) + scale_x_continuous(labels = function(x) paste0(x, 
      ""), name = "", breaks = seq(2001, 2020, by = 2), 
      limits = c(2000, 2021), expand = c(0, 0)) + theme_bw() + theme(axis.line = element_line(), panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), panel.border = element_blank(), 
      panel.background = element_blank()) + theme(legend.position = c(0.25, 
      0.8))+ plotTheme 
  }
  else if (isTRUE(stochastic)) {
    
    
    data_perc <- read_csv(url(stochastic.url), col_names = TRUE, 
      na = c(""), skip_empty_rows = TRUE, col_types = NULL)
    data_perc <- data.frame(data_perc)
    
    data_perc <- cbind(seq(2019, 2052, by = 1), data_perc)
    data_perc[, 2:4] <- data_perc[, 2:4] * 100
    colnames(data_perc) <- c("year", "X25", "X50", "X75")
    data_perc <- data.frame(data_perc)

    graph <- ggplot(data_perc, aes(x = year, y = `X25`)) + 
      geom_col(aes(x = year, y = `X75`, fill = "Range of Reasonable Outcomes"), 
        alpha = stochastic.alpha) + 
      geom_col(aes(x = year, y = `X25`), fill = "white") + 
      geom_line(aes(x = year, y = `X50`, color = "Median"), size = 2) + 
      scale_fill_manual(values = c(palette_reason$DarkBlue, "white", palette_reason$Orange)) + 
      theme(panel.grid.major.y = element_line(colour = "white", 
      size = 3)) + scale_y_continuous(labels = function(x) paste0(x, 
      "%"), breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), name = "Funded Ratio (Actuarial Value)", 
      expand = c(0, 0)) + scale_color_manual(values = c(palette_reason$Orange)) + 
      ggplot2::theme(axis.ticks.x = element_line(size = 0.5, 
        color = "black")) + ggplot2::theme(axis.ticks.y = element_line(size = 0.5, 
      color = "black")) + scale_x_continuous(labels = function(x) paste0(x, 
      ""), name = "", breaks = seq(2020, 2053, by = 2), 
      limits = c(2020, 2053), expand = c(0, 0)) + theme_bw() +
      theme(axis.line = element_line(), panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(), panel.border = element_blank(), 
      panel.background = element_blank()) + theme(legend.position = c(0.25, 
      0.8))+ plotTheme 
  }
  else if (isTRUE(compound.gl)) {
    urlfile = gl.url
    data <- read_csv(url(urlfile), col_names = TRUE, na = c(""), 
      skip_empty_rows = TRUE, col_types = NULL)
    data <- as.data.table(data)
    data <- data %>% replace(is.na(.), 0)
    data <- data.frame(data)
    data2 <- data.frame(data)
    for (i in (2:(length(data[, 1])))) {
      data2[i, 2:length(data)] <- data2[i, 2:length(data)] + 
        data2[(i - 1), 2:length(data)]
    }
    data2 <- data.table(data2 %>% mutate_all(as.numeric))
    reason.data <- data.frame(data2)
    colnames(reason.data) <- c("year", lab1, lab2, lab3, 
      lab4, lab5, lab6, if (!is_null(lab7)) {
        paste(lab7)
      }, if (!is_null(lab8)) {
        paste(lab8)
      }, if (!is_null(lab9)) {
        paste(lab9)
      })
    names <- colnames(reason.data)
    graph <- ggplot(reason.data) + geom_col(aes(x = year, 
      y = reason.data[, 2] * yaxisScale, fill = str_wrap(as.character(names[2]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 3] * yaxisScale, fill = str_wrap(as.character(names[3]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 4] * yaxisScale, fill = str_wrap(as.character(names[4]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 5] * yaxisScale, fill = str_wrap(as.character(names[5]), 
        str)), position = "stack") + geom_col(aes(x = year, 
      y = reason.data[, 6] * yaxisScale, fill = str_wrap(as.character(names[6]), 
        str)), position = "stack") + geom_line(aes(x = year, 
      y = reason.data[, length(names)] * yaxisScale, color = str_wrap(paste(last(names)), 
        str)), size = 1.25) + ggplot2::geom_hline(yintercept = 0, 
      color = "black") + scale_fill_manual(values = c(palette_reason$LightRed, 
      palette_reason$Orange, palette_reason$LightOrange, 
      palette_reason$Green, palette_reason$Red, palette_reason$Yellow, 
      palette_reason$SatBlue)) + scale_color_manual(values = c("black")) + 
      theme_bw() + theme(axis.line = element_line(), 
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
      panel.border = element_blank(), panel.background = element_blank()) + 
      theme(legend.position = "right") + theme(legend.title = element_blank()) + 
      labs(x = element_blank(), y = "Compound Unfunded Actuarial Liability (in $ Billions)") + 
      ggplot2::scale_x_continuous(breaks = seq(min(reason.data$year), 
        max(reason.data$year), by = 2), expand = c(0, 
        0)) + ggplot2::scale_y_continuous(labels = function(x) paste0("$", 
      x), breaks = seq(Ymin, Ymax, by = Ybreak), limits = c(Ymin, 
      Ymax), expand = c(0, 0)) + if (!is.null(lab7)) {
      geom_col(aes(x = year, y = reason.data[, 7] * yaxisScale, 
        fill = str_wrap(as.character(names[7]), str)), 
        position = "stack") + plotTheme
    }
    else if (!is.null(lab7) & !is.null(lab8)) {
      geom_col(aes(x = year, y = reason.data[, 7] * yaxisScale, 
        fill = str_wrap(as.character(names[7]), str)), 
        position = "stack") + geom_col(aes(x = year, 
        y = reason.data[, 8] * yaxisScale, fill = str_wrap(as.character(names[8]), 
          str)), position = "stack")
    }
    else if (!is.null(lab7) & !is.null(lab8) & !is.null(lab9)) {
      geom_col(aes(x = year, y = reason.data[, 7] * yaxisScale, 
        fill = str_wrap(as.character(names[7]), str)), 
        position = "stack") + geom_col(aes(x = year, 
        y = reason.data[, 8] * yaxisScale, fill = str_wrap(as.character(names[8]), 
          str)), position = "stack") + geom_col(aes(x = year, 
        y = reason.data[, 9] * yaxisScale, fill = str_wrap(as.character(names[9]), 
          str)), position = "stack")
    }
  }
  if (isTRUE((interactive))) {
    graph <- ggplotly(graph)
  }
  graph
}

###################

stochasticERC2 <- barPlot2(
  data = NULL, 
  net.amo = FALSE, 
  contributions = FALSE, 
  compound.gl = FALSE,
  gl.url = "https://raw.githubusercontent.com/ReasonFoundation/GraphicsR/master/PERSI_GL2.csv",
  str = 25,
  stochastic = TRUE, 
  stochastic.url = "https://raw.githubusercontent.com/ANiraula/SCRS_FModel/main/SCRS.FModel_ERC_Statutory_Stoch_Cons.csv",
  Ymax = 30,
  Ymin = 0,
  Ybreak = 2,
  yaxisScale = 1/1000000000, 
  stochastic.alpha = 0.55,
  interactive = FALSE,
  lab1 = "Investment Experience", 
  lab2 = "Benefit Changes",
  lab3 = "Changes to Actuarial Methods & Assumptions",
  lab4 = "Deviations from Demographic Assumptions",
  lab5 = "Negative Amortization",
  lab6 = "Gains From Pay Increases Not Given",
  lab7 = "Net Change to Unfunded Liability",
  lab8 = NULL,
  lab9 = NULL)

stochasticERC2
```
